WebApp/Controllers/AccountController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WebApp.Entities;

namespace WebApp.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class AccountController : ControllerBase
    {
        private readonly SignInManager<IdentityUser> _signInManager;

        public AccountController(SignInManager<IdentityUser> signInManager)
        {
            _signInManager = signInManager;
        }
        // return user info
        public async Task<IActionResult> ExternalLoginCallback()
        {
            var LoginInfo = await _signInManager.GetExternalLoginInfoAsync();
            if (LoginInfo is not null)
            {
                var emailClaim = LoginInfo.Principal.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email);
                var NameClaim = LoginInfo.Principal.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name);

                if (emailClaim is not null && NameClaim is not null)
                {
                    var user = new IdentityUser { Email = emailClaim.Value, UserName = NameClaim.Value };
                    await _signInManager.SignInAsync(user, false);
                }
            }
            return RedirectToPage("/Index");
        }
    }
}

WebApp/Pages/Account/ConfirmEmail.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages.Account
{
    public class ConfirmEmailModel : PageModel
    {
        [BindProperty]
        public string Message { get; set; }

        private readonly UserManager<IdentityUser> _userManager;

        public ConfirmEmailModel(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }
        public async Task<IActionResult> OnGetAsync(string userId,string token)
        {
            var user = await _userManager.FindByIdAsync(userId);

            if(user is not null)
            {
                var result = await _userManager.ConfirmEmailAsync(user, token);
                if (result.Succeeded)
                {
                    this.Message = "Email Address Successfully confirmd,you can now try to login";
                    return Page();
                }   
            }
            this.Message = "Failed To Validate Email";
            return Page();
        }
    }
}

WebApp/Pages/Account/Login.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Entities;

namespace WebApp.Pages.Account
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;

        public LoginModel(SignInManager<IdentityUser> signInManager)
        {
            _signInManager = signInManager;
        }
        [BindProperty]
        public Credential Credential { get; set; }

        [BindProperty]
        public IEnumerable<AuthenticationScheme> AuthenticationProviders { get; set; }
        public async Task OnGetAsync()
        {
            this.AuthenticationProviders = await _signInManager.GetExternalAuthenticationSchemesAsync();
        }

        

        public async Task<IActionResult> OnPostAsync()
        {
            if(!ModelState.IsValid) return Page();

            var result = await _signInManager.PasswordSignInAsync(Credential.Email,
                Credential.Password,
                Credential.RememberMe,
                false);

            if(result.Succeeded)
            {
                return RedirectToPage("/Index");
            }
            ModelState.AddModelError("Login", "Failed to login");
            return Page();
        }

        public IActionResult OnPostLoginExternally(string provider)
        {
            // properties contains some info about user
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider,null);
            properties.RedirectUri = Url.Action("ExternalLoginCallback", "Account");

            return Challenge(properties,provider);
        }
    }
}

WebApp/Pages/Account/Logout.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages.Account
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;

        public LogoutModel(SignInManager<IdentityUser> signInManager)
        {
            _signInManager = signInManager;
        }
        public async Task<IActionResult> OnPostAsync()
        {
            await _signInManager.SignOutAsync();
            return RedirectToPage("/Account/Login");
        }
    }
}

WebApp/Pages/Account/Register.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net;
using System.Net.Mail;
using WebApp.Entities;

namespace WebApp.Pages.Account
{
    public class RegisterModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;

        public RegisterModel(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }
        [BindProperty]
        public RegisterModelView RegisterModelView { get; set; }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if(!ModelState.IsValid) return Page();
            // create user

            var user = new IdentityUser
            {
                Email = RegisterModelView.Email,
                UserName = RegisterModelView.Email,
            };
           var result = await _userManager.CreateAsync(user, RegisterModelView.Password);

            if (result.Succeeded)
            {
                var confirmationToken = await _userManager.GenerateEmailConfirmationTokenAsync(user);
               var confirmationLink = Redirect(Url.PageLink(pageName:"/Account/ConfirmEmail",
                   values: new {userId = user.Id, token = confirmationToken}));

                var message = new MailMessage("hassan19alsayed@gmail.com",
                    RegisterModelView.Email,
                    "please confirm your email",
                    $"please click here to confirm your email address {confirmationLink}");

                using (var emailClient = new SmtpClient("smtp-relay.brevo.com", 587))
                {
                    emailClient.Credentials = new NetworkCredential(
                        "781724001@smtp-brevo.com",
                        "s36TNgBYRmOQCxUW"
                        );
                    await emailClient.SendMailAsync(message);
                }
                return RedirectToPage("/Account/Login");
            }
            result.Errors.ToList().ForEach(e => ModelState.AddModelError("Register", e.Description));
            return Page();
        }
    }
}

WebApp/Pages/Account/ConfirmEmail.cshtml
@page
@model WebApp.Pages.Account.ConfirmEmailModel
@{
}

<br />
<p>
    @Model.Message
</p>

WebApp/Pages/Account/Login.cshtml
@page
@model WebApp.Pages.Account.LoginModel
@{
}
<h3>User Login</h3>
<br />
<div class="container border" style="padding:20px">
    <form method="post">
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="Credential.Email"></label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="Credential.Email" class="form-control" />
                <span asp-validation-for="Credential.Email" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="Credential.Password"></label>
            </div>
            <div class="col-5">
                <input type="password" asp-for="Credential.Password" class="form-control" />
                <span asp-validation-for="Credential.Password" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 check">
            <div class="col-2">
                <input type="checkbox" class="form-check-input" asp-for="Credential.RememberMe" />
                <label class="form-check-label" asp-for="Credential.RememberMe"></label>
            </div>
            <div class="col-5">
            </div>
        </div>
        <div class="mb-3 row">
            <div class="col-2">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
            <div class="col-5">
            </div>
        </div>
        <br />
        <p>
            Social Media Logins:
            <div class="form-group">
                @foreach(var provider in Model.AuthenticationProviders)
                {
                    <button type="submit"
                        asp-page-handler="LoginExternally"
                        name="provider"
                        value="@provider.Name"
                        class="btn btn-primary"
                    >
                     Login With @provider.DisplayName
                    </button>
                }
            </div>
        </p>
    </form>

</div>

WebApp/Pages/Account/Logout.cshtml
@page
@model WebApp.Pages.Account.LogoutModel
@{
}

WebApp/Pages/Account/Register.cshtml
@page
@model WebApp.Pages.Account.RegisterModel
@{
}
<div class="container border" style="padding:20px">
    <div asp-validation-summary="All" class="text-danger"></div>
    <form method="post">
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="RegisterModelView.Email"></label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="RegisterModelView.Email" class="form-control" />
                <span asp-validation-for="RegisterModelView.Email" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="RegisterModelView.Password"></label>
            </div>
            <div class="col-5">
                <input type="password" asp-for="RegisterModelView.Password" class="form-control" />
                <span asp-validation-for="RegisterModelView.Password" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row">
            <div class="col-2">
                <input type="submit" value="Register" class="btn btn-primary" />
            </div>
            <div class="col-5">
            </div>
        </div>
    </form>

</div>